version: '3.8'

services:
  # 1. Base de datos MySQL
  innovatech-db:
    image: mysql:8.0
    container_name: innovatech-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innovatech_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Tu servicio Backend (Java Spring Boot)
  innovatech-back:
    build:
      context: ./innovatech-backend
      dockerfile: Dockerfile
    container_name: innovatech-back
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://innovatech-db:3306/innovatech_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - innovatech-db

  # 3. Tu servicio Frontend (React)
  innovatech-front:
    build:
      context: ./Innovatech-frontend
      dockerfile: Dockerfile
    container_name: innovatech-front
    ports:
      - "80:80"
    depends_on:
      - innovatech-back

volumes:
  mysql_data:
