version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Cambia a la ruta real de tu carpeta front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://tu-ip-o-dominio-ec2:3000
    depends_on:
      - backend
    networks:
      - red-innovatech

  backend:
    build:
      context: ./backend   # Cambia a la ruta real de tu carpeta back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=usuario_prod
      - DB_PASSWORD=secreto_seguro
      - DB_NAME=innovatech_db
    depends_on:
      - db
    networks:
      - red-innovatech
    volumes:
      - backend_logs:/app/logs # Ejemplo de persistencia en backend

  db:
    image: postgres:15-alpine # O mysql:8, según lo que uses
    environment:
      - POSTGRES_USER=usuario_prod
      - POSTGRES_PASSWORD=secreto_seguro
      - POSTGRES_DB=innovatech_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistencia crítica exigida en la pauta
    networks:
      - red-innovatech

volumes:
  db_data:      # Named volume para asegurar que los datos no se pierdan al reiniciar
  backend_logs:

networks:
  red-innovatech:
    driver: bridge
