name: Deploy Innovatech to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy and Run Docker via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          echo "¡Conectado con éxito a AWS!"
          mkdir -p /home/ubuntu/proyecto-innovatech-unico
          cd /home/ubuntu/proyecto-innovatech-unico
          sudo docker-compose down --remove-orphans || true
          if [ -d ".git" ]; then
            sudo git reset --hard
            sudo git pull origin main
          else
            sudo git clone https://github.com/Sebakm13/INNOVATECH-TRABAJO.git .
          fi
          sudo docker-compose up --build -d
          sudo docker ps
