name: Pipeline CI/CD Monorepo Innovatech

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # CAJITA 1: Compilar y verificar (Build)
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar entorno de simulación
      run: |
        echo "Validando estructura de Innovatech-frontend..."
        echo "Validando estructura de innovatech-backend..."
        echo "Código listo para ser desplegado."

  # CAJITA 2: El despliegue real en tu servidor AWS (Deploy)
  deploy-to-aws:
    runs-on: ubuntu-latest
    needs: build-and-push # Esto hace que aparezca la línea que une las dos cajitas
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Desplegar en AWS EC2 vía SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          echo "¡Conectado con éxito a AWS!"
          mkdir -p /home/ubuntu/proyecto-innovatech-unico
          cd /home/ubuntu/proyecto-innovatech-unico
          sudo docker-compose down --remove-orphans || true
          if [ -d ".git" ]; then
            sudo git reset --hard
            sudo git pull origin main
          else
            sudo git clone https://github.com/Sebakm13/INNOVATECH-TRABAJO.git .
          fi
          sudo docker-compose up --build -d
          sudo docker ps
